horizonal-verify:	horizontal-partition.cpp
	g++ horizontal-partition.cpp -o horizontal-verify -lm -fopenmp

horizontal-perf:	horizontal-partition.cpp
	g++ horizontal-partition.cpp -o horizontal-perf -lm -fopenmp